### ISSUE TITLE
Issues in any of the upscaling functions

### ISSUE THREAD

**Issue by Specy** [Tenpi/waifu2x#12]
So, i'm using v0.6.7, upscaleImage() doesn't work, nor does any of the other functions. I did some minor debugging to what i had provided and saw that the command being executed by upscaleImage() function is the following:

```
cd C:\Users\dione\Desktop\Progetti\electron\scapix\node_modules\waifu2x\waifu2x/ && waifu2x-converter-cpp.exe -i "C:\Users\dione\Desktop\14fsfd.jpg" -o "C:\Users\dione\Desktop\up\10-2\/14fsfd.jpg" -s 
--scale-ratio 2
```
Note the \/ in the output path, i think that's what is causing the issue, i'm going to test a bit using path.join() and let you know.

EDIT: i changed 
https://github.com/Tenpi/waifu2x/blob/bcbf6d6fa0c406f467a15c2930a0a99dc0881f15/waifu2x.ts#L131

to: 
`destPath = path.join(folder,image)`

didn't solve the issue but i think you should change that part anyway

**Comment by Specy** [comment]
Wait, i didn't have the issue when i was using v0.4.3 , in v0.4.4 you changed the waifu2x binary to something else, from that moment it stopped working, if i use the "waifu2x-converter-cpp.exe" from command line, that one also doesn't work, what did you change it with?

**Comment by Moebytes** [comment]
> Wait, i didn't have the issue when i was using v0.4.3 , in v0.4.4 you changed the waifu2x binary to something else, from that moment it stopped working, if i use the "waifu2x-converter-cpp.exe" from command line, that one also doesn't work, what did you change it with?

Yeah, I upgraded it to v5.3.4, but I will downgrade it to v5.3.3 since it might be a buggy release. The `\/` thing is still a valid path on Windows, that shouldn't be a problem. I call `path.normalize(dest)` anyways at the end, so it should now output a prettier path.

**Comment by Moebytes** [comment]
Please see if `0.6.8` fixes your problems.

**Comment by Specy** [comment]
in 0.6.8 upscaleImage, upscaleGif, works perfectly but im again having the issues with getting fps info from the video, i'm getting error:
```
Error TypeError: Cannot read property '0' of null
[1]     at C:\Users\dione\Desktop\Progetti\electron\scapix\node_modules\waifu2x\dist\waifu2x.js:506:65[1]     at step (C:\Users\dione\Desktop\Progetti\electron\scapix\node_modules\waifu2x\dist\waifu2x.js:33:23)
[1]     at Object.next (C:\Users\dione\Desktop\Progetti\electron\scapix\node_modules\waifu2x\dist\waifu2x.js:14:53)
[1]     at fulfilled (C:\Users\dione\Desktop\Progetti\electron\scapix\node_modules\waifu2x\dist\waifu2x.js:5:58)
[1]     at runMicrotasks (<anonymous>)
[1]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
this without using ffprobe. The video i've tried is the same 30 seconds one i sent before

**Comment by Moebytes** [comment]
> in 0.6.8 upscaleImage, upscaleGif, works perfectly but im again having the issues with getting fps info from the video

The 30 seconds vid works fine for me. If you can check the regex functions `parseFramerate`, `parseDuration`, let me know which one is giving you an error.

**Comment by Specy** [comment]
Ok firstly, the issue was in parseDuration, not parseFramerate, secondly, i can't seem to reproduce the error, i think it might have just been a permission error or something, i'll update you if it happens again.

Also to note, video is still a TINNY bit longer, original is 30.09s, upscaled is 30.16, it's noticeable while listening to audio but i have no idea what would be causing it.
