### ISSUE TITLE
Is it possible to make it use already separated images for videos? 

### ISSUE THREAD

**Issue by JFMugen** [Tenpi/waifu2x#13]
So we can stop/resume it whenever we want. It would be very handy for longer videos (especially for people with old hardware like me)

**Comment by Moebytes** [comment]
No, you should never have a "partial" folder of images. When you stop early it renders the video up to that point and deletes the images folder. Also, it will cause a confliction when upscaling the same video multiple times concurrently.

This is not suitable for long videos, I would recommend that you use another tool like [dandere2x](https://github.com/akai-katto/dandere2x).

**Comment by JFMugen** [comment]
Well, it looks like an awesome alternative. Thank you!

**Comment by Moebytes** [comment]
Just an update to mention that this was added as of the latest version `v0.8.2`, so it's possible to stop a download/turn off your computer etc. and it will resume where it left off. Now the frames are only deleted on a 100% completion.
