### ISSUE TITLE
Issue with stopping the progress right at 0 ( reason in thread )

### ISSUE THREAD

**Issue by trudenpa** [Tenpi/waifu2x#19]
So since I want to check whether an image is still stuck at its current image ( 0 ) because of it taking way too long to render/upscale, I thought about doing current === 0 if condition. 
The purpose of me doing this is to avoid having huge lag spikes because of my RAM/GPU messing up after like a minute so any image that's upscaling past a minute should get rejected. 

The issue is that current === 0 does absolutely nothing compared to anything that's higher to 0. If a total of 1+ image has been upscaled, I can suddenly cancel those. But this has no point if it takes me a lot of time to upscale before I can reject it as it defeats its purpose.
I tried stuff like adding a promise to resolve + returning true but they don't seem to work either, the image still upscales regardless.

It would be nice if I could limit the images to something like canceling after a specific amount of time, I am super confused.
If I missed something that already does this, please let me know. The whole reason is to avoid issues with RAM/GPU etc

**Comment by Moebytes** [comment]
You probably want to use `upscaleImage`, this is the full definition of the function
```ts
public static upscaleImage = async (source: string, dest?: string, options?: Waifu2xOptions, action?: () => "stop" | void)
```
It takes a final callback parameter where if you return the words "stop", it will send a SIGINT signal to the waifu2x process and stop it.

All of the functions that work on multiple images, such as `upscaleImages`, `upscaleGIF`, and `upscaleVideo` can only be stopped on a full frame, not in the middle of an upscale, reason being it's pretty pointless to run those if you can't even upscale 1 of the images.
