### ISSUE TITLE
Video/Gif cleanup on cancel

### ISSUE THREAD

**Issue by Specy** [Tenpi/waifu2x#26]
Currently when stopping a video/gif from upscaling the temp folder where the frames are located is not deleted, i guess this is to implement the resume feature. I'd suggest to expose a option that ignores this behaviour and does cleanup regardless

**Comment by Moebytes** [comment]
Set the `noResume` property to true and it will always delete the frame folder, thus making it impossible for it to resume, but that's what you asked for.

**Comment by Specy** [comment]
Thanks!
