### ISSUE TITLE
real-esrgan upscaler not working 

### ISSUE THREAD

**Issue by DikaArdnt** [Tenpi/waifu2x#28]
My code :

const { default: waifu } = require('waifu2x')

let progress = (percent: number) => {
  console.log(`Percent: ${percent}`)
  if (percent > 50) return true
}
await waifu.upscaleImage("./temp/ex.jpg", "./temp/ex-scaled.jpg", { scale: 4, upscaler: "real-esrgan" }, progress)

**Comment by Moebytes** [comment]
On MacOS you have to run the provided `chmod777` function at least once.

`waifu.chmod777()`
