### ISSUE TITLE
Option to use Absolute path as file input and output 

### ISSUE THREAD

**Issue by Specy** [Tenpi/waifu2x#3]
Currently the module allows for relative path to be used, that would mean having to copy the file in the current working folder as a temp file and then  running it through the module, it would be good to have an option like { absolutePath: true } which uses the [sourcePath](https://github.com/Tenpi/waifu2x/blob/d8643bbeff1fd8e97d26ce97d579f21148e2e036/Waifu2x.ts#L101) and destPath directly without being modified, example would be:

```
waifu2x.upscaleImage("C:\Users\someUser\Desktop\image.png","C:\Path\To\Program\image.jpg", {scale: 2, absolutePath: true})
```

waifu2x automatically changes file extension when using a different format in the output file so it can be fed directly, code wise it would be: 
```
let command = `cd ${pathToWaifu2x} && waifu2x-converter-cpp.exe -i "${path}" -o "${endPath}"`
//plus the options of course
```
or similar

**Comment by Specy** [comment]
Oh and another useful thing would be a function that just gets a string as input and runs it as a command returning a promise for the stdout

**Comment by Moebytes** [comment]
Ok, please upgrade to `v0.1.9` which adds the `absolutePath` option... Note that I also changed how you input the options for the GIF. Now you pass an object:
```ts
await waifu2x.upscaleGIF("./image.gif", "./gifs", {constraint: 30})
```
As for your second request... I didn't see it earlier, but you should be able to just use `child_process.exec` directly.

**Comment by Specy** [comment]
Thanks a lot, sorry for bothering so much with this, there shouldn't be more add-ons needed for now

**Comment by Moebytes** [comment]
> Thanks a lot, sorry for bothering so much with this, there shouldn't be more add-ons needed for now

It's fine, I don't mind.
