### ISSUE TITLE
Waifu2x.upscaleImage is not a function.

### ISSUE THREAD

**Issue by JeshMate** [Tenpi/waifu2x#30]
ive imported it correctly into a mjs file
`import Waifu2x from "waifu2x";`
and ive provided a base image i want to upscale but regardless of it being correct. it is saying:
`TypeError: Waifu2x.upScaleImage is not a function`
ive tried looking through the export functions and it all looks good, read the documentation and still to no avail.

**Comment by Moebytes** [comment]
Check capitalization

**Comment by JeshMate** [comment]
According to the exports in the package, what's said in the TypeError contains correct capitalization.
