### ISSUE TITLE
Wierd behavior when running in arm64

### ISSUE THREAD

**Issue by PlaryWasTaken** [Tenpi/waifu2x#32]
When upscaling images or GIFs in an arm based machine, the function finishes almost instantly, without errors and without generating the upscaled file.
```js
const waifu2x = require("waifu2x")

(async () => {
    await waifu2x.upscaleImage("./image.png", "./upscaled.png", {
        upscaler: "waifu2x"
    })
})()
```
Code that i used to test, tested with all default upscalers, waifu2x, real-esrgan and real-cugan.
Any leads on what could cause this strange behavior?

**Comment by Moebytes** [comment]
On macOS you have to run the chmod777 function to set execution permissions on the binaries. You may also have to go in and right click -> open each, because they are unverified they will refuse to run the first time.

**Comment by PlaryWasTaken** [comment]
> On macOS you have to run the chmod777 function to set execution permissions on the binaries. You may also have to go in and right click -> open each, because they are unverified they will refuse to run the first time.

Im using linux with an Ampere arm cpu, even after modifying the script to run the chmod777 function, it doenst work or error.
I also did further testing, Windows 11 x86 with gpu runs fine, Linux x86 with gpu runs fine, Linux x86 without gpu works for real_cugan and waifu2x (real_esrgan doenst seem to support cpu mode), Linux arm64 does not work with any

**Comment by PlaryWasTaken** [comment]
After compiling real-cugan from source, and changing the binary, real-cugan upscaler now works as intended.
Should i look into the source code and see if i can make the library throw an error when it finds an incompatible binary?
I will look into compiling waifu2x from source too and update this issue with my results since i dont yet even know whether waifu2x can be compiled to arm

**Comment by Moebytes** [comment]
The provided binaries are compiled for x64 linux and will not run on arm64 without translation software. You will need to use the linux equivalent of Rosetta 2, quick search found me this: https://box86.org/ 

You could also compile each of the programs from source. You can open a pull request to add them but this project is approaching the maximum allowed npm package size and I don't know if they will fit. 
https://github.com/nihui/waifu2x-ncnn-vulkan 
https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan 
https://github.com/nihui/realcugan-ncnn-vulkan

**Comment by Moebytes** [comment]
should work now
