### ISSUE TITLE
waifu2x.upscaleImage is not a function

### ISSUE THREAD

**Issue by Haliq0841** [Tenpi/waifu2x#33]
Please make a testing example (es module) I have done what is explained in the readme 
```
import waifu2x from "waifu2x" 
await waifu2x.upscaleImage() 
```
but the response is like this
 ```
TypeError: waifu2x.upscaleImage is not a function 
```
So, if you can, just make an example test

**Comment by Moebytes** [comment]
on javascript you probably have to use `waifu2x.default`. Can you try printing it and see what it is?

**Comment by Haliq0841** [comment]
turns out it works, thanks for the help. I will close this issue. 
But I have a suggestion for the next update, just use the Canvas Module from NPMJS because the one on GitHub has an error or can't be imported, so I'm forced to only install the old version.

**Comment by Haliq0841** [comment]
> on javascript you probably have to use `waifu2x.default`. Can you try printing it and see what it is?

turns out it works, thanks for the help. I will close this issue. But I have a suggestion for the next update, just use the Canvas Module from NPMJS because the one on GitHub has an error or can't be imported, so I'm forced to only install the old version.

**Comment by Moebytes** [comment]
What node.js version are you using? Make sure you have the latest version: https://nodejs.org/en 

I can't use the one on npm because it contains a bug and I cannot compile it.

**Comment by Haliq0841** [comment]
I'm already using the latest version of node.js (nodejs_21), but still can't install, like the response you see below:
![20240225_153614](https://github.com/Tenpi/waifu2x/assets/131313850/3717266f-1afe-46bb-8084-f82eed3d7115)

**Comment by Haliq0841** [comment]
> What node.js version are you using? Make sure you have the latest version: https://nodejs.org/en
> 
> I can't use the one on npm because it contains a bug and I cannot compile it.

I'm already using the latest version of node.js (nodejs_21), but still can't install, like the response you see below:
![20240225_153614](https://github.com/Tenpi/waifu2x/assets/131313850/7f83da87-f7d7-4ebf-af03-1cbe4e8b7603)
and error when installing the canvas module

**Comment by Moebytes** [comment]
To build it you need to install Microsoft Visual C++ Build Tools: https://visualstudio.microsoft.com/downloads/?q=build+tools 

If you still can't install it you are better off asking them as it's an issue with their repo. https://github.com/Automattic/node-canvas 

Canvas is only used to get images from a PDF so if you don't want to upscale PDF's you don't need it. I will try to find an alternative way to do it since it's true that this dependency is a pain to install.

**Comment by Moebytes** [comment]
Update to 1.4.0 I dropped the canvas dependency
