### ISSUE TITLE
update so that it actually works?

### ISSUE THREAD

**Issue by Pomax** [Tenpi/waifu2x#34]
Followed the `npm install` instruction and immediate ran into highly questionable behaviour
```
d:\temp>npm install waifu2x
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\Pomax\AppData\Local\npm-cache\_logs\2024-07-12T23_34_32_085Z-debug-0.log
```
Why is something trying to open a file _during dependency installation_?

**Comment by Moebytes** [comment]
You need to install where there is a package.json file.

**Comment by Pomax** [comment]
Why? That's not a thing packages need to do, `npm` gets to modify package.json content, but your just-installed-package does not.

**Comment by Moebytes** [comment]
Every package needs to open the package.json, you get that error when it doesn't exist. 
https://nodesource.com/blog/an-absolute-beginners-guide-to-using-npm/ 

Regardless, npm issues are not relevant to this repository, you have to go to the npm repo.

**Comment by Pomax** [comment]
They absolutely don't, I can install anything I've  ever needed without one, but _this_ package throws an error, so that's not `npm`'s problem, this package is doing something weird.

Install express in an empty dir: not a problem.

![image](https://github.com/user-attachments/assets/dc68fc64-dbaa-4dc4-b41f-630e263f9583)

Install esbuild? Sure, of course that works:

![image](https://github.com/user-attachments/assets/1c889ddd-496e-4553-9ca8-3d5e3470fcf8)

Install _this_ package? Error.

![image](https://github.com/user-attachments/assets/08e2dfcf-f599-431a-9f17-14b85c43e392)

You package really is doing something that other package simply don't. And please, by all means, confirm this by running `npm install express` or `npm install esbuild` in completely empty directories yourself: that works. It's _supposed_ to work. But _something_ (and that might not be you, but one of your dependencies) breaks the install.
 
Something's trying to run the linux/macos `open` command, which thankfully doesn't exist on Windows, so whatever it was trying to do turns into an error instead.

**Comment by Moebytes** [comment]
That was never supposed to work I don't see anywhere in their documentation where you can install npm packages without a package.json. I don't even see the motivation why you want to do that. Just do things the correct way and it installs fine 

npm init -y
npm install waifu2x

**Comment by Pomax** [comment]
Quoting [the NPM documentation](https://docs.npmjs.com/downloading-and-installing-packages-locally):

> **Note**: If there is no package.json file in the local directory, the latest version of the package is installed.
>
> If there is a package.json file, npm installs the latest version that satisfies the [semver rule](https://docs.npmjs.com/about-semantic-versioning) declared in package.json.

NPM has never needed a package.json just to install things (although it absolutely needs one for a number of other subcommands, of course).

That said: even _with_ a package.json, we (of course) get exactly the same error:

![image](https://github.com/user-attachments/assets/93a1f67a-30cb-44e1-b9a4-680ef9c7f16c)

**Comment by Pomax** [comment]
Looks like the culprit is `graceful-fs` somewhere in your dependency chain. 

```
173 verbose stack Error: ENOENT: no such file or directory, open
173 verbose stack     at open (node:fs:565:11)
173 verbose stack     at go$open (D:\nvm\v20.11.0\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:357:14)
173 verbose stack     at Object.open (D:\nvm\v20.11.0\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:354:12)
173 verbose stack     at [_open] (D:\nvm\v20.11.0\node_modules\npm\node_modules\tar\node_modules\fs-minipass\index.js:271:8)
173 verbose stack     at new WriteStream (D:\nvm\v20.11.0\node_modules\npm\node_modules\tar\node_modules\fs-minipass\index.js:248:18)
173 verbose stack     at [file] (D:\nvm\v20.11.0\node_modules\npm\node_modules\tar\lib\unpack.js:402:20)
173 verbose stack     at [makeFs] (D:\nvm\v20.11.0\node_modules\npm\node_modules\tar\lib\unpack.js:686:26)
173 verbose stack     at D:\nvm\v20.11.0\node_modules\npm\node_modules\tar\lib\unpack.js:630:30
173 verbose stack     at callback (D:\nvm\v20.11.0\node_modules\npm\node_modules\graceful-fs\polyfills.js:306:20)
173 verbose stack     at FSReqCallback.oncomplete (node:fs:201:21)
174 verbose cwd d:\temp\_
175 verbose Windows_NT 10.0.19045
176 verbose node v20.11.0
177 verbose npm  v10.2.4
178 error code ENOENT
179 error syscall open
180 error errno -4058
181 error enoent ENOENT: no such file or directory, open
182 error enoent This is related to npm not being able to find a file.
182 error enoent
```

**Comment by Pomax** [comment]
(note that you won't run into this if you forgot that you have a dependency on third party tool packs, like unixtools, mingw32, msys2, etc. Basically anything that installs the standard unix toolset on windows will hide this error, and it's _super_ easy to forget you have those installed)

**Comment by Moebytes** [comment]
The error is that it can't open the root of your directory `d:\temp\_`, firstly it is very weird to name it "_" and you are bound to run into issues with scripts not expecting that. Second you need to verify the process has permission to write to this location in folder permissions (or run powershell as administrator).

Third, some people who had this error recommended clearing npm cache:
`npm cache clean --force`

Lastly, I forgot to mention that this is a big package because of all included binaries for windows/mac/linux, you will need at least 300MB of free space to download it. You can remove the binaries you won't use after its installed.

**Comment by Pomax** [comment]
No it isn't, the error is very clear in that `open` cannot be found (e.g. it's not a file or dir in both the current working directory, nor the PATH). hence the error:

- first `ENOENT` for "(there) E(xists) NO ENT(ry)", then
- the human-readable explanation, `no such file or directory`, and then last
- the entry that doesn't exist, in this case `open`.

(Also, dir related: no, `_` is a perfectly normal character on all operating systems, there's nothing weird about it being at the start of a dirname rather than the more common "in the middle". The OS doesn't care. You might think it looks weird, but it's functionally identical to normal letters)

That said: this is almost certainly not "your" fault, since your own dependencies don't include `graceful-fs`, but it _is_ something that may need to be pointed out in the README.md: Windows users are going to need to have a working `open` command. And I'm pretty sure you do (open a cmd prompt or powershell and run `open` to check that) and that's why you're not seeing this error, but standard Windows installations do not come with `open`, and so without additional steps plenty of folks will not be able to install this.

**Comment by Moebytes** [comment]
I don't have this issue on windows so it is something to do with your environment. Do you use windows 11 or an older version?

In the error, `open` is not the file being opened, but the command. The file being opened is an empty string, which is why you don't see it, but it basically means its the root of where you run the command

**Comment by Pomax** [comment]
Windows 10 (can't update to 11 due to the mandatory microsoft account), although that should behave pretty much identical to 11 in this respect. Any idea what the empty string is? (because if this happens even in an dir with a package.json, then there's not much more I can do as someone running the install command)

**Comment by Moebytes** [comment]
does it work if you use command prompt? `open` doesn't seem to be a powershell command.

**Comment by Pomax** [comment]
no dice in either `cmd` or `powershell` it looks like

**Comment by Moebytes** [comment]
I don't know what else it could be sorry. You might get more answers on the npm repo. This seems more like npm issue than with my project

**Comment by Pomax** [comment]
fair enough, I'll see if I can isolate it to something I can file an issue for in a better place.
