### ISSUE TITLE
Waifu2x-caffe vs waifu2x-cpp

### ISSUE THREAD

**Issue by Specy** [Tenpi/waifu2x#5]
Do you think that switching to the Caffe version could be an improvement? 
I saw that it has more settings and higher support for models but don't know of drawbacks or if it can be used in this module. I saw that it has a CLI version so maybe it could be.

**Comment by Moebytes** [comment]
File size. waifu2x-cpp is a lot lighter at ~100MB, but when I downloaded waifu2x-caffe the size was over 1GB. 100MB is still huge for a npm package, but it's a lot more manageable than 1GB.

**Comment by Specy** [comment]
Mhm Strange, the whole  Caffe GUI is 120mb zipped so I hoped it would still be manageable

**Comment by Moebytes** [comment]
I'm going to stick with waifu2x-cpp, since it's the lightest out of all the options for Windows.
